version: 2

models:
    - name: {{ schema }}.{{ table }}
      columns:
    {%- for column in columns %}
        - name: {{ column["name"] }}
          description: 
          tests:
            - not_null
    {%- endfor -%}