version: 2

models:
    - name: {{ entity }}
      columns:
    {%- for column in columns %}
        - name: {{ column["name"] }}
          description: {{ column["name"] }}
          tests:
            - not_null
    {%- endfor -%}